### ISSUE TITLE
Comment / rename cryptic variables

### ISSUE THREAD

**Issue by vvasuki** [drdhaval2785/SanskritVerb#124]
Looking at the code, one does not easily realize what (say) "cond17" is in the [main file](https://github.com/drdhaval2785/SanskritVerb/blob/master/tiGanta.php#L284), unless one does a [search](https://github.com/drdhaval2785/SanskritVerb/search?utf8=%E2%9C%93&q=cond17) across files. This is an impediment to easily understanding / reading the code.

Potential solutions:
- Add a comment wherever (say) "cond17" is used.
- Rename cond17 to condMantraAkarmaka or condMantraAkarmakaNa

Note: There are comments such as /* upAnmantrakaraNe (1.3.25) */ , which sort-of help. But, conditions are different from prescriptions that are to be applied when conditions are met - so that's inadequate.

**Comment by drdhaval2785** [comment]
It is doable. The issue is that there are many layers of user input required for some of the derivation. It is better to have some number rather than a text as variable name. Otherwise I would have to search for numerous variables.
e.g. cond17_1 === 1 would mean that condition 17.1.1 is satisfied.

For now I have written the following comment after the first occurrence of such 'cond' variables.
```
cond stands for condition. They are taken from user input. For all variables having cond as prefix, details can be seen at ajax requirement.docx.
```

[ajax requirement.docx](https://github.com/drdhaval2785/SanskritVerb/blob/master/ajax%20requirement.docx) is the file where all conditions for user input are specified.

**Comment by drdhaval2785** [comment]
It is also mentioned in the frontend in the following manner.
```
Places where we take user input can be accessed [here](lanover.com/lan/sanskrit/SanskritVerb/ajax%20requirement.docx). 
```
