### ISSUE TITLE
डुदाञ् दाने - लट् लकारः

### ISSUE THREAD

**Issue by sowmyakrishnapur** [drdhaval2785/SanskritVerb#197]
-> The prakriya shows ददा directly after श्लौ। Application of ह्रस्वः (७.४.५९) is not listed
-> The application of तिप् and शप् should be after removing the इत्संज्ञा - If इत्संज्ञा letter is not removed first, at the stage of डुदाञ्, doubling would be for डु and not for दा
-> Some irrelevant sutras like By īdūtau ca saptamyarthe (1.1.19)  are being listed in the prakriya
-> In dvivachana and bahuvachana, sutras which require अभ्यस्तसंज्ञा (श्नाभ्यस्तयोरातः, अदभ्यस्तात्) are applied first, and अभ्यस्तसंज्ञा is given later...

**Comment by drdhaval2785** [comment]
Thank you very much ma'am for your interest in the machine.
Let me first of all place my gratitude. I learnt siddhAntakaumudI with help of your lectures.

`-> The prakriya shows ददा directly after श्लौ। Application of ह्रस्वः (७.४.५९) is not listed`
Corrected.

`-> The application of तिप् and शप् should be after removing the इत्संज्ञा - If इत्संज्ञा letter is not removed first, at the stage of डुदाञ्, doubling would be for डु and not for दा`
Pending.

`-> Some irrelevant sutras like By īdūtau ca saptamyarthe (1.1.19) are being listed in the prakriya`
It was because of a numbering issue. One version of SK had 'dAdhA ghvadAp' as 1.1.20 and another one had 1.1.19. My database had it at 1.1.20. By error, I had written the rule number as 1.1.19, so wrong sUtra was displayed. Corrected now.

`-> In dvivachana and bahuvachana, sutras which require अभ्यस्तसंज्ञा (श्नाभ्यस्तयोरातः, अदभ्यस्तात्) are applied first, and अभ्यस्तसंज्ञा is given later...`
Corrected.

**Comment by drdhaval2785** [comment]
The pending issue is noted at #198.
Closing this issue

**Comment by sowmyakrishnapur** [comment]
Wow! Those corrections were carried out really fast! You are doing an
amazing work, Dhaval-mahodaya.. Abhinandanaani. Your tools are extremely
useful for all Vyakarana enthusiasts...

About the corrections, a few comments below -

On 19 October 2015 at 22:00, Dr. Dhaval Patel <notifications@github.com>
wrote:

> Thank you very much ma'am for your interest in the machine.
> Let me first of all place my gratitude. I learnt siddhAntakaumudI with
> help of your lectures.
>
> -> The prakriya shows ददा directly after श्लौ। Application of ह्रस्वः
> (७.४.५९) is not listed
> Corrected.
>

Yes. I can see the application of ह्रस्वः now. But the tool shows ददा ति
after both श्लौ and ह्रस्वः।  It should be

श्लौ
दादा

ह्रस्वः
ददा

> -> The application of तिप् and शप् should be after removing the इत्संज्ञा
> - If इत्संज्ञा letter is not removed first, at the stage of डुदाञ्,
> doubling would be for डु and not for दा
> Pending.
>
> -> Some irrelevant sutras like By īdūtau ca saptamyarthe (1.1.19) are
> being listed in the prakriya
> It was because of a numbering issue. One version of SK had 'dAdhA ghvadAp'
> as 1.1.20 and another one had 1.1.19. My database had it at 1.1.20. By
> error, I had written the rule number as 1.1.19, so wrong sUtra was
> displayed. Corrected now.
>

Could it be similar issue with आतो लोप इटि च (६.४.६४) in दा+तस्? That sutra
is not applicable for this form...

> -> In dvivachana and bahuvachana, sutras which require अभ्यस्तसंज्ञा
> (श्नाभ्यस्तयोरातः, अदभ्यस्तात्) are applied first, and अभ्यस्तसंज्ञा is
> given later...
> Corrected.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/drdhaval2785/SanskritVerb/issues/197#issuecomment-149271807>
> .
>



-- 
Sowmya

**Comment by drdhaval2785** [comment]
```
But the tool shows ददा ति after both श्लौ and ह्रस्वः।
```
Corrected now.
```
Could it be similar issue with आतो लोप इटि च (६.४.६४) in दा+तस्? That sutra is not applicable for this form
```
No. I forgot to code for अजादौ. Therefore, even with तस्‌ the rule applied erraneously.
Now corrected.

**Comment by drdhaval2785** [comment]
@sowmyakrishnapur 
The changes have been installed in live server.

**Comment by sowmyakrishnapur** [comment]
Thanks. I noticed a few other things.. Would you prefer me to email them,
or raise them as issues in github?

Sowmya

On 20 October 2015 at 15:22, Dr. Dhaval Patel <notifications@github.com>
wrote:

> @sowmyakrishnapur <https://github.com/sowmyakrishnapur>
> The changes have been installed in live server.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/drdhaval2785/SanskritVerb/issues/197#issuecomment-149499460>
> .
>



-- 
Sowmya

**Comment by drdhaval2785** [comment]
@sowmyakrishnapur 
I would prefer issues in github. 
It helps to document things in right perspective.
When at a later stage, I may want to document the bug corrections - github issues would help.

Try to keep one single topic in single issue.
It keeps them manageable and closable.
