### ISSUE TITLE
जुहोत्यादि - intermediate forms not shown

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#200]
#197 raised an issue that the intermediate alterations in the juhotyAdi dhAtus are not shown properly.
e.g. 
`qudAY -> dAdA -> dadA` is the proper sequence.

Right now we are following sahajabodha system of Pushpa Dikshit, in which she gave a final verb directly after application of rules of abhyasa etc.
As @sowmyakrishnapur mentioned, the rules are not displayed properly with their outcomes in juhotyAdi.

@mrudani 
The question which remains is 
Can anyone of you write an interim derivation for the following juhotyAdi set ?
```
जुहोत्यादि=("ऋ","कि","कित!","गा","घृ","जन!","तुर!","डुदाञ्","धन!","डुधाञ्","धिष!","णिजि!र्","पृ","पॄ","भस!","ञिभी","डुभृञ्","माङ्","विजि!र्","विषॢ!","सृ","ओ!हाङ्","ओ!हाक्","हु","हृ","ह्री");
```
Note - ! stands for anunAsika जनँ / धनँ इत्यादि

Expected outcome is 
```
जुहोत्यादि=("इऋ","किकि","किकित्","गिगा","घिघृ","जजन्","तुतुर्","ददा","दधन्","दधा","दिधिष्","नेनिज्","पिपृ","पिपॄ","बभस्","बिभी","बिभृ","मिमा","वेविज्","वेविष्","सिसृ","हिहा","हहा","हुहु","हिहृ","जिह्री");
```

Can you explain one by one the derivation of each verb with necessary sUtras?
One verb in one comment.

**Comment by mrudani** [comment]
ऋधातोः लकारविवक्षायां, लस्य तिबादीनामादेशे,  शप् विकरणे, जुहोत्यादिभ्यः श्लुः इति शपः श्लु(लोपः),
श्लौ इति धातोः द्वित्वे, ऋ ऋ इति जाते 
"अर्त्तिपिपर्त्योश्च" इति अभ्सासस्य इत् आदेशः 
उरण् रपरः इति रपरो भूत्वा स आदेशः भवति इर् ऋ
हलादिः शेषः इति सूत्रेण हलादिशेषे 'इऋ' इति भवति

**Comment by mrudani** [comment]
किधातोः श्लौ इति द्वित्वे किकि इति.

**Comment by mrudani** [comment]
कित्-धातोः 'श्लौ' इति द्वित्वे कित् कित्
हलादिशेषः इति सूत्रेण हलादिशेषे किकित्.

**Comment by mrudani** [comment]
गा इति छान्दसः धातुः
श्लौ इति द्वित्वे गा गा
बहुलं छन्दसि इति अभ्यासस्य इत्वे गिगा

**Comment by mrudani** [comment]
घृधातोः श्लौ इति सूत्रेण द्वित्वे घृ घृ
धातुरयं छान्दसः, बहुलं छन्दसि अभ्यासस्य इत्वं घिघृ.

**Comment by sowmyakrishnapur** [comment]
In all these, there is also the application of कुहोश्चुः (७.४.६२) and
अभ्यासे चर्च (८.४.५४), in addition to what you have mentioned.

कि -> किकि -> चिकि
गा -> गागा -> गगा -> गिगा -> जिगा
घृ -> घृ घृ -> घर्घृ -> घघृ -> झघृ -> झिघृ -> जिघृ

अभ्यासकार्य-s are of two types - General operations, which are applicable
in all cases of dvitva, and those which are specific to जुहोत्यादिगण. Among
the general kaaryas, these five are applicable -

ह्रस्वः ७.४.५९
हलादिः शेषः ७.४.६०
कुहोश्चुः ७.४.६२
उरत् ७.४.६६
अभ्यासे चर्च ८.४.५४

You have already implemented these for लिट् लकार, so repeating them for
this gana should not be difficult.

Following four are the operations specific to juhotyaadigana
निजां त्रयाणां गुणः श्लौ ७.४.७५
भृञामित् ७.४.७६
अर्तिपिपर्त्योश्च ७.४.७७
बहुलं छन्दसि ७.४.७८

If you are interested, you can look at the two attached presentations which
discuss in detail dvitva for juhotyaadigana (I am teaching this gana
currently in my tinantaprakriya class, which is why I tried out those
dhaatus on your machine first).

Regards,
Sowmya



2015-10-20 17:29 GMT+05:30 mrudani <notifications@github.com>:

> घृधातोः श्लौ इति सूत्रेण द्वित्वे घृ घृ
> धातुरयं छान्दसः, बहुलं छन्दसि अभ्यासस्य इत्वं घिघृ.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/drdhaval2785/SanskritVerb/issues/200#issuecomment-149541508>
> .
>



-- 
Sowmya

**Comment by drdhaval2785** [comment]
@mrudani 
Very good. This is the kind of derivation I wanted. It helps. Please go ahead for the rest of them.
@sowmyakrishnapur 
Github issues replied via emails usually don't allow attachments like normal mails.
Would you please forward the presentations to drdhaval2785@gmail.com?

**Comment by drdhaval2785** [comment]
Now the most of the intermediate steps are shown (not sure).
Closing this issue for now.
If any intermediate form is missing, please open a new issue.
