### ISSUE TITLE
हलि च (८.२.७७)

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#255]
/* hali ca (8.2.77) */
$rvverb=array("ir","Ir","Ir","ur","kIv","kur","kfv","klIv","kziv","kzIv","kzIv","kzur","kzur","Kur","Kur","gir","gur","gUr","gUr","Gur","GUr","cir","cIv","cIv","cur","cUr","Cur","jIv","jur","jUr","tir","1tIv","tIv","3tIv","tur","tUr","div","div","div","dIv","dIv","DIv","Dur","Dur","Druv","niv","nIv","pIv","pur","pUr","Bur","mIv","mIv","mur","mur","mUr","mUr","rIv","SUr","Sriv","SrIv","zWiv","zWIv","siv","siv","sIv","sur","sUr","sTiv","sPur","sriv","srIv","hur",);
// pending to code for how to apply this to whole $rvverb. Right now just coded for pratidivan

**Comment by gasyoun** [comment]
So many arrays. Sure you need a MySQL database, @drdhaval2785

**Comment by drdhaval2785** [comment]
@gasyoun 
http://stackoverflow.com/questions/18706301/massive-php-array-vs-mysql-database says that PHP arrays are faster than Database queries.
As most of our data is static with no addition / deletion, arrays should be fine.

Once we have some active addition / deletions in database contemplated, I will sure go for MySQL. Meanwhile trying to learn it.

**Comment by funderburkjim** [comment]
I suggest you consider using sqlite rather than mysql.

* sqlite access is built-in to modern versions of PHP  (PDO-Sqlite)
* sqlite requires no additional server.  With Mysql you have to set up and manage a separate server.
  XAMPP seems to make this easy, but
* Ease of transfer to another server.   With sqlite, you just move a file .  With mysql it's more complicated.
* sqlite is fast, so no MYsql advantage there.  

Mysql might be better for big commercial activities.  But I think Sqlite is excellent for research-level
Sanskrit computation.


If you decide to use a database and want to try sqlite, I can point out to you the places where
sqlite files are created and accessed in the Cologne Sanskrit-Lexicon system.

**Comment by drdhaval2785** [comment]
Jim, will definitely consider sqlite as suggested by you. If I get stuck, i
will get back.

**Comment by drdhaval2785** [comment]
```
/* hali ca (8.2.77) */
elseif ( in_array($so,$tiG) && arr($text,'/[rv]\+/') && sub(array("i","u","f"),array("r+","v+"),$halAdi_apit_sArvadhAtuka_pratyayas,0) )
{
    $text=three(array("i","u","f"),array("r+","v+"),$halAdi_apit_sArvadhAtuka_pratyayas,array("I","U","F"),array("r+","v+"),$halAdi_apit_sArvadhAtuka_pratyayas,0);
	storedata('8.2.77','sa',0);
}
```
Was coded when coding the tiGanta thing.
