### ISSUE TITLE
अङ्क लुङ्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#265]
आञ्चकत् इति भवेत्
अङ्क णिच् लुङ्
णकारचकारयोः इत्संज्ञायां अङ्क इ लुङ्
लुङः तिप् - अङ्क इ तिप्
णिश्रिद्रुस्रुभ्यः कर्तरि चङ् इति चङि - अङ्क इ चङ् तिप्
अतो लोपः इति अलोपे प्राप्ते, चङि इति द्वित्वे च प्राप्ते
द्विर्वचनेचि इति सूत्रेण आदौ द्वित्व एव
अजादेर्द्वितीयस्य इति द्वितीयैकाचः द्वित्वे, नन्द्राः संयोगादयः इति ङकारस्य द्वित्वं न
ककारस्य द्वित्वे अङ्कक इ चङ् तिप्
कुहोश्चुः इति कस्य चत्वे अङ् च क इ चङ् तिप्
ङकारस्य परसवर्णे अञ् च क इ चङ् तिप्
अतो लोपः इति अलोपे अञ्चक् इ चङ् तिप्
चकारङकारपकाराणामित्संज्ञायां लोपे - अञ्चक् इ अ ति
आडजादीनामिति आडागमे आ अञ्चक् इ अ ति
आटश्च वृद्धौ आञ्चक् इ अ ति
इतश्च इति तिपः इकारलोपे - आञ्चक् इ अ त्
णेरनिटि इति णिचः लोपे आञ्चकत् इति रूपम्

**Comment by drdhaval2785** [comment]
Why not आञ्चिकत्‌ ?
अङ्क+णि+अ+त्‌
अङ्कि+अत्
अङ्किकि+अत्‌
अङ्चिकि+अत्‌
अङ्चिक्‌+अत्‌
अञ्चिकत्‌
आ+अञ्चिकत्‌
आञ्चिकत्‌ 

Why does अतो लोपः not apply before द्वित्व ?
In आटिटत्‌ etc, there was अतो लोपः first and then द्वित्व by द्विर्वचनेऽचि । अटि+अत्‌->अटिटि+अत्‌->अटिटत्‌->आटिटत्‌
So why not आञ्चिकत्‌ by the same logic ?
@mrudani or @raghubhaijoshi would like to shed some light.

**Comment by drdhaval2785** [comment]
Currently the machine gives the following output
```
आञ्चिकद्-(अङ्क,लुङ्,तिप्,चुरादि,१०।०४७३)
आञ्चिकत्-(अङ्क,लुङ्,तिप्,चुरादि,१०।०४७३)
आञ्चिकतः-(अङ्क,लुङ्,तस्,चुरादि,१०।०४७३)
आञ्चिक-(अङ्क,लुङ्,झि,चुरादि,१०।०४७३)
आञ्चिकः-(अङ्क,लुङ्,सिप्,चुरादि,१०।०४७३)
आञ्चिकथः-(अङ्क,लुङ्,थस्,चुरादि,१०।०४७३)
आञ्चिकथ-(अङ्क,लुङ्,थ,चुरादि,१०।०४७३)
आञ्चिकम्-(अङ्क,लुङ्,मिप्,चुरादि,१०।०४७३)
आञ्चिकावः-(अङ्क,लुङ्,वस्,चुरादि,१०।०४७३)
आञ्चिकामः-(अङ्क,लुङ्,मस्,चुरादि,१०।०४७३)
आञ्चिकत-(अङ्क,लुङ्,त,चुरादि,१०।०४७३)
आञ्चिकाताम्-(अङ्क,लुङ्,आताम्,चुरादि,१०।०४७३)
आञ्चिकान्त-(अङ्क,लुङ्,झ,चुरादि,१०।०४७३)
आञ्चिकथाः-(अङ्क,लुङ्,थास्,चुरादि,१०।०४७३)
आञ्चिकाथाम्-(अङ्क,लुङ्,आथाम्,चुरादि,१०।०४७३)
आञ्चिकध्वम्-(अङ्क,लुङ्,ध्वम्,चुरादि,१०।०४७३)
आञ्चिके-(अङ्क,लुङ्,इट्,चुरादि,१०।०४७३)
आञ्चिकावहि-(अङ्क,लुङ्,वहि,चुरादि,१०।०४७३)
आञ्चिकामहि-(अङ्क,लुङ्,महिङ्,चुरादि,१०।०४७३)
```

**Comment by drdhaval2785** [comment]
OK.
The issue is discussed in 

चङि (६.१.११) in काशिका
पचादीनां ण्यनतानाम् चङि कृते णिलोपः, उपधाह्रस्वत्वं, द्विर्वचनम् इत्येषां कार्याणां प्रवृत्तिक्रमः।

न्यासः

अत्रेदानीं द्विर्वचनं प्राप्नोति णिलोपश्च; द्वयोरपि कृताकृतप्रसङ्गित्वान्नित्यत्वम्(), ततश्चोभयोस्तुल्यबलत्वात्? परत्वाण्णिलोपः। "आटिटत्()" इति। अत्रापि णिलोपे कृते णिलोपस्य स्थानिवत्वादद्विर्वचनं भवत्येव। स्थानिवद्भावस्तु "द्विर्वचनेऽचि" १।१।५८ इत्यनेन। णिलोपोऽपि नित्यः, अकृतेऽपि द्विर्वचने तेन भवितव्यम्(), कृतेऽपि। न च शब्दान्तरप्राप्तिः, द्विष्प्रयोगो द्विर्वचनं भवतीति कृत्वा। स्थाने द्विर्वचनं त्वत्र न स्वीक्रियते; लक्ष्यानुरोधात्()। ततश्चोभयोस्तुल्यबलयोः परत्वाणिणलोपः।

**Comment by drdhaval2785** [comment]
I have coded according to the answer of kAzikA.
If there is any issue cropping up due to this, it would be noted separately.
Closing this issue for now.

![capture](https://cloud.githubusercontent.com/assets/5755132/12371389/de2405c0-bc57-11e5-84c0-a25c85c84c4e.png)
